### ISSUE TITLE
Navbar-component

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#10]
**Task title**
Navbar-component

**Task description**
Creat the navbar component

**Subtasks**

- [x] add logo
- [x] Home link
- [x] Blogs link
- [x] about dropdown
- [x] contact us link
- [x] Log In button

**Screenshots**
![navbar](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/26eaa584-69d7-4b15-85b7-9165089be722)

**Link to the component on Figma**
Put the link here

**Comment by M07am3dM** [comment]
Done.
