### ISSUE TITLE
Footer-component

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#11]
**Task title**
Footer-component

**Task description**
Creat the footer component

**Subtasks**

- [x] subscribe field
- [x] page links
- [x] socials icons

**Screenshots**
![footerr](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/a4025f41-ca7d-49a6-8a55-7ced4d104bdd)

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-6892&mode=design&t=YB5vmlBgRYGp1CFQ-4

**Comment by M07am3dM** [comment]
Done.
