### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#12]
**Task title**
Home page

**Task description**
Creat the home page, wich containe 6 sections

**Subtasks**

- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27

**Screenshots**

1. hero section
![hero](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/220436ac-de55-4366-991f-0a0b662fdb66)

2. section 2
![section 2](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/c87c280e-e05d-4692-b805-3695294c9383)

3. section 3
![section3](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/dd9f677c-560e-4747-bd7f-420e2231c7a3)

4. section 4
![section 4](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/83f87baa-da68-48b5-b65f-59352741dd46)

5. section 5
![tickets](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/d6219644-a0f9-4d9f-8f7b-61b1eb97e997)

6. section 6
![section6](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/d5eeaecd-34c3-4448-906d-ac6e5efb2798)

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?node-id=2%3A6773&mode=dev

**Comment by M07am3dM** [comment]
Done.

**Comment by dzc0d3r** [comment]
Closed .. see PRs  #43 #47 #48 #49 #55
