### ISSUE TITLE
about team page

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#18]
**Task title**
about team page

**Task description**
creat about team page feature our team members with short profiles. These profiles should include photos, names, roles, and a brief description of each member's.

**Subtasks**

- [x] develop about the team page

**Screenshots**
![Capture d’écran 2023-10-14 201211](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/3c35b196-b813-453f-ba96-2b9c5c9cec1c)

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-6360&mode=design&t=iYcMyvxa9t3sNrbw-4

**Comment by M07am3dM** [comment]
This issue are closed, look PR #111.
