### ISSUE TITLE
careers page

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#19]
**Task title**
careers page

**Task description**
develop a "Careers" page that will serve as a portal for job seekers interested in joining our team. This page will provide job listings, application details, and insights into our company culture.

**Subtasks**

- [x] Job Listings : Display our current job openings with detailed descriptions, including roles, requirements, and responsibilities.

- [x] Company Culture : Offer a glimpse into our company culture and values to help candidates understand our work environment and ethos.

**Screenshots**
![Capture d’écran 2023-10-14 201351](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/2f17b45e-575d-4573-a7db-0b81a652de7d)

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-6255&mode=design&t=iYcMyvxa9t3sNrbw-4

**Comment by M07am3dM** [comment]
Done.
