### ISSUE TITLE
Therapist Profile Page

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#20]
**Task title**
Therapist Profile Page

**Task description**
create a  therapist Profile page 

**Subtasks**

- [x] Display user-specific data
- [x] therapist can view and edit their personal information

**Screenshots**
![Capture d’écran 2023-10-14 203441](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/9ff4d77c-18fb-447b-a893-7971c1c345a2)

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-5628&mode=design&t=iYcMyvxa9t3sNrbw-4

**Comment by dzc0d3r** [comment]
closed see #97
