### ISSUE TITLE
Home page section 4 : Recent BLOGs

### ISSUE THREAD

**Issue by M07am3dM** [202306-NEA-DZ-FEW/online-Therapist#25]
**Task title**
Recent blogs section

**Description**
---
Recent blogs section, where we show the latest blog articles with a slider to navigate between the blogs cards as shown in the design

**Subtasks**

- [x] #38

**Screenshot**
---
![Blogs](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/49822541/c6a13599-fce7-4dd7-b2fc-20c7d011470b)

**Link**
---
Figma [design](https://www.figma.com/file/ae4wheNUlDfAcNOmxj13Xy/Online-Therapist?type=design&node-id=279-4753&mode=design&t=7DROxNinUEMUaY0E-4)

**Comment by dzc0d3r** [comment]
Closed ... ref see #55
