### ISSUE TITLE
therapist requirements page

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#28]
**Task title**
therapist requirments page

**Task description**
creat a therapist requirments page, This page outlines the key reasons to work with Healing and the requirements for joining our counseling network.

**Subtasks**

- [x] Why Work with Healing 
- [x] the Requirements
- [x] get started button that takes to the therapist creat page

**Screenshots**
![requirment](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/29c5828e-dabe-4577-bdfa-b5681bae02ab)

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-6015&mode=design&t=iYcMyvxa9t3sNrbw-4

**Comment by M07am3dM** [comment]
Done.
