### ISSUE TITLE
Therapist profil create

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#29]
**Task title**
Therapist profil create page

**Task description**
develop a page that allow the therapiste to creat an account

**Subtasks**

- [x] #61
- [x] #58
- [x] #62

**Screenshots**
![Capture d’écran 2023-10-15 001153](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/6bd36df6-1b2f-40b0-9c61-305e5066cbbc)
![Capture d’écran 2023-10-15 001101](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/88b14349-a43d-4ee2-9373-96bef4242ce9)

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-5955&mode=design&t=iYcMyvxa9t3sNrbw-4

**Comment by dzc0d3r** [comment]
closed see #73
