### ISSUE TITLE
the user saved cards page 

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#30]
**Task title**
Payment Methods

**Task description**
Put the description here (Mandatory)

**Subtasks**
Put the subtasks here if any (optional)

**Screenshots**
![Capture d’écran 2023-10-15 003128](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/b81165a8-02e0-4f7b-bcad-e21a28b83e42)

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-4846&mode=design&t=iYcMyvxa9t3sNrbw-4

**Comment by dzc0d3r** [comment]
closed see #70
