### ISSUE TITLE
Create SuggestedBlogCard as a reusable component.

### ISSUE THREAD

**Issue by dzc0d3r** [202306-NEA-DZ-FEW/online-Therapist#38]
**Description**
---
Create a SuggestedBlogsCard as a reusable component to use it in different places .. see screenshots below .

**Screenshots**
---
![Blogs](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/49822541/76ac57fd-dbe9-4196-aaa0-4fe5e2bf9a31)
![Recommended(1)](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/49822541/acfad686-ff75-4d4e-be16-9870bc79eda7)

**Links**
Home page [figma design](https://www.figma.com/file/ae4wheNUlDfAcNOmxj13Xy/Online-Therapist?type=design&node-id=279-4694&mode=design&t=7DROxNinUEMUaY0E-4)
Single blog article[ figma design](https://www.figma.com/file/ae4wheNUlDfAcNOmxj13Xy/Online-Therapist?type=design&node-id=279-4626&mode=design&t=7DROxNinUEMUaY0E-4)
Blog card https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?node-id=2%3A6813&mode=dev

**Comment by M07am3dM** [comment]
Done.
