### ISSUE TITLE
deploy the project

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#6]
**Task title**
deploy the project

**Task description**
deploy the project  to continuously test the website in a real environment. This helps in identifying and addressing issues as they arise, reducing the chances of major problems surfacing later.

**Subtasks**

- [x] Deploy the project to Vercel or Netlify

**Comment by M07am3dM** [comment]
I did the deployment to Vercel.
@dzc0d3r , @Lilicod please checkout the pull request so we can finish all the project setup.

**Comment by dzc0d3r** [comment]
@Lilicod 
@M07am3dM 
I will close the issue :tada: 

---
closed .. see #36
