### ISSUE TITLE
add translation to home page and fix the buttons

### ISSUE THREAD

**Issue by dzc0d3r** [202306-NEA-DZ-FEW/online-Therapist#71]
**Task title**
add translation to the home page and fix the buttons.

**Task description**
Translate the sections that needs translation in the home page: hero section, communication section, appointment section, are you a councelor section, tickets section and fix the buttons in hero section and appointment section

**Subtasks**
N/A

**Screenshots**
---
Sections that need translation 
**hero**
![Screenshot 2023-10-30 at 16-53-16 https __innerspace netlify app](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/49822541/9b3273e9-63ca-4325-bfa4-c05f2ef07d30)

**appointment**
![Screenshot 2023-10-30 at 16-55-23 https __innerspace netlify app](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/49822541/3e477f35-9d17-4962-8031-90bafc96e488)

**Communication**

**Recent blogs**
![Screenshot 2023-10-30 at 17-05-00 https __innerspace netlify app](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/49822541/b6644199-5c5f-4cf2-b4e3-174e78e6fa6c)

**Tickets** 

**Are you a councelor**

**Link to the component on Figma**
N/A

**Comment by Lilicod** [comment]
closes #89
