### ISSUE TITLE
Creating and Customizing 404 Page

### ISSUE THREAD

**Issue by meryem08** [202306-NEA-DZ-FEW/online-Therapist#90]
**Task title**
Creating and Customizing 404 Page

**Task description**
In this issue, we'll focus on creating a custom 404 page for our website. A 404 page is displayed when a user attempts to access a page that doesn't exist, providing them with a user-friendly and informative error page. Our goals for this issue include:

- Designing a visually appealing and 404 page.
- Adding clear error messaging to guide users back to valid pages.
- Providing links to essential areas of our website, such as the homepage.

**Comment by Lilicod** [comment]
closed in #102
